[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
repository = "https://git.t1a.cloud/mike.perlov/sas-lexer.git"
authors = ["Mike Perlov <mishamsk@gmail.com>"]
version = "0.1.0"
publish = false

[workspace.dependencies]
sas_lexer = { path = "crates/sas_lexer" }

insta = { version = "1.39.0", features = ["yaml"] }
rstest = "0.21.0"
serde = { version = "1.0.204", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }

[workspace.lints.rust]
unsafe_code = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -2 }
# # Allowed pedantic lints
# char_lit_as_u8 = "allow"
# collapsible_else_if = "allow"
# collapsible_if = "allow"
# implicit_hasher = "allow"
# map_unwrap_or = "allow"
# match_same_arms = "allow"
# missing_errors_doc = "allow"
# missing_panics_doc = "allow"
# module_name_repetitions = "allow"
# must_use_candidate = "allow"
# similar_names = "allow"
# too_many_lines = "allow"
# needless_raw_string_hashes = "allow"
# # Disallowed restriction lints
# print_stdout = "warn"
# print_stderr = "warn"
# dbg_macro = "warn"
# empty_drop = "warn"
# empty_structs_with_brackets = "warn"
# exit = "warn"
# get_unwrap = "warn"
# rc_buffer = "warn"
# rc_mutex = "warn"
# rest_pat_in_fully_bound_structs = "warn"
