[package]
name = "sas_lexer"
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[dependencies]
strum = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
