name: Publish to Test PyPI

on:
  workflow_dispatch:

jobs:
  build-wheels:
    uses: ./.github/workflows/build-py-wheels.yml

  pypi-publish:
    name: Upload to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      # For PyPI's trusted publishing.
      id-token: write
    steps:
      - name: "Install uv"
        uses: astral-sh/setup-uv@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish to PyPi
        run: uv publish -v --publish-url https://test.pypi.org/legacy/ wheels/*
